/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as KiteCallbackRouteImport } from './routes/kite/callback'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppNewMeRouteImport } from './routes/_app/new-me'
import { Route as AppHoldingsRouteImport } from './routes/_app/holdings'
import { Route as AppHabitsRouteImport } from './routes/_app/habits'
import { Route as AppCashflowRouteImport } from './routes/_app/cashflow'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'
import { Route as AppAttackModeRouteImport } from './routes/_app/attack-mode'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAttackModeIndexRouteImport } from './routes/_app/attack-mode/index'
import { Route as AppAttackModeProblemsRouteImport } from './routes/_app/attack-mode/problems'
import { Route as AppAttackModeJournalRouteImport } from './routes/_app/attack-mode/journal'
import { Route as AppAttackModeGoalsRouteImport } from './routes/_app/attack-mode/goals'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const KiteCallbackRoute = KiteCallbackRouteImport.update({
  id: '/kite/callback',
  path: '/kite/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNewMeRoute = AppNewMeRouteImport.update({
  id: '/new-me',
  path: '/new-me',
  getParentRoute: () => AppRoute,
} as any)
const AppHoldingsRoute = AppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackModeRoute = AppAttackModeRouteImport.update({
  id: '/attack-mode',
  path: '/attack-mode',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackModeIndexRoute = AppAttackModeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttackModeRoute,
} as any)
const AppAttackModeProblemsRoute = AppAttackModeProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AppAttackModeRoute,
} as any)
const AppAttackModeJournalRoute = AppAttackModeJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppAttackModeRoute,
} as any)
const AppAttackModeGoalsRoute = AppAttackModeGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppAttackModeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/attack-mode': typeof AppAttackModeRouteWithChildren
  '/budget': typeof AppBudgetRoute
  '/cashflow': typeof AppCashflowRoute
  '/habits': typeof AppHabitsRoute
  '/holdings': typeof AppHoldingsRoute
  '/new-me': typeof AppNewMeRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/kite/callback': typeof KiteCallbackRoute
  '/attack-mode/goals': typeof AppAttackModeGoalsRoute
  '/attack-mode/journal': typeof AppAttackModeJournalRoute
  '/attack-mode/problems': typeof AppAttackModeProblemsRoute
  '/attack-mode/': typeof AppAttackModeIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/accounts': typeof AppAccountsRoute
  '/budget': typeof AppBudgetRoute
  '/cashflow': typeof AppCashflowRoute
  '/habits': typeof AppHabitsRoute
  '/holdings': typeof AppHoldingsRoute
  '/new-me': typeof AppNewMeRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/kite/callback': typeof KiteCallbackRoute
  '/': typeof AppIndexRoute
  '/attack-mode/goals': typeof AppAttackModeGoalsRoute
  '/attack-mode/journal': typeof AppAttackModeJournalRoute
  '/attack-mode/problems': typeof AppAttackModeProblemsRoute
  '/attack-mode': typeof AppAttackModeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/attack-mode': typeof AppAttackModeRouteWithChildren
  '/_app/budget': typeof AppBudgetRoute
  '/_app/cashflow': typeof AppCashflowRoute
  '/_app/habits': typeof AppHabitsRoute
  '/_app/holdings': typeof AppHoldingsRoute
  '/_app/new-me': typeof AppNewMeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/kite/callback': typeof KiteCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/attack-mode/goals': typeof AppAttackModeGoalsRoute
  '/_app/attack-mode/journal': typeof AppAttackModeJournalRoute
  '/_app/attack-mode/problems': typeof AppAttackModeProblemsRoute
  '/_app/attack-mode/': typeof AppAttackModeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/accounts'
    | '/attack-mode'
    | '/budget'
    | '/cashflow'
    | '/habits'
    | '/holdings'
    | '/new-me'
    | '/settings'
    | '/tasks'
    | '/kite/callback'
    | '/attack-mode/goals'
    | '/attack-mode/journal'
    | '/attack-mode/problems'
    | '/attack-mode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/accounts'
    | '/budget'
    | '/cashflow'
    | '/habits'
    | '/holdings'
    | '/new-me'
    | '/settings'
    | '/tasks'
    | '/kite/callback'
    | '/'
    | '/attack-mode/goals'
    | '/attack-mode/journal'
    | '/attack-mode/problems'
    | '/attack-mode'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_app/accounts'
    | '/_app/attack-mode'
    | '/_app/budget'
    | '/_app/cashflow'
    | '/_app/habits'
    | '/_app/holdings'
    | '/_app/new-me'
    | '/_app/settings'
    | '/_app/tasks'
    | '/kite/callback'
    | '/_app/'
    | '/_app/attack-mode/goals'
    | '/_app/attack-mode/journal'
    | '/_app/attack-mode/problems'
    | '/_app/attack-mode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  KiteCallbackRoute: typeof KiteCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/kite/callback': {
      id: '/kite/callback'
      path: '/kite/callback'
      fullPath: '/kite/callback'
      preLoaderRoute: typeof KiteCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-me': {
      id: '/_app/new-me'
      path: '/new-me'
      fullPath: '/new-me'
      preLoaderRoute: typeof AppNewMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/holdings': {
      id: '/_app/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof AppHoldingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashflow': {
      id: '/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-mode': {
      id: '/_app/attack-mode'
      path: '/attack-mode'
      fullPath: '/attack-mode'
      preLoaderRoute: typeof AppAttackModeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-mode/': {
      id: '/_app/attack-mode/'
      path: '/'
      fullPath: '/attack-mode/'
      preLoaderRoute: typeof AppAttackModeIndexRouteImport
      parentRoute: typeof AppAttackModeRoute
    }
    '/_app/attack-mode/problems': {
      id: '/_app/attack-mode/problems'
      path: '/problems'
      fullPath: '/attack-mode/problems'
      preLoaderRoute: typeof AppAttackModeProblemsRouteImport
      parentRoute: typeof AppAttackModeRoute
    }
    '/_app/attack-mode/journal': {
      id: '/_app/attack-mode/journal'
      path: '/journal'
      fullPath: '/attack-mode/journal'
      preLoaderRoute: typeof AppAttackModeJournalRouteImport
      parentRoute: typeof AppAttackModeRoute
    }
    '/_app/attack-mode/goals': {
      id: '/_app/attack-mode/goals'
      path: '/goals'
      fullPath: '/attack-mode/goals'
      preLoaderRoute: typeof AppAttackModeGoalsRouteImport
      parentRoute: typeof AppAttackModeRoute
    }
  }
}

interface AppAttackModeRouteChildren {
  AppAttackModeGoalsRoute: typeof AppAttackModeGoalsRoute
  AppAttackModeJournalRoute: typeof AppAttackModeJournalRoute
  AppAttackModeProblemsRoute: typeof AppAttackModeProblemsRoute
  AppAttackModeIndexRoute: typeof AppAttackModeIndexRoute
}

const AppAttackModeRouteChildren: AppAttackModeRouteChildren = {
  AppAttackModeGoalsRoute: AppAttackModeGoalsRoute,
  AppAttackModeJournalRoute: AppAttackModeJournalRoute,
  AppAttackModeProblemsRoute: AppAttackModeProblemsRoute,
  AppAttackModeIndexRoute: AppAttackModeIndexRoute,
}

const AppAttackModeRouteWithChildren = AppAttackModeRoute._addFileChildren(
  AppAttackModeRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAttackModeRoute: typeof AppAttackModeRouteWithChildren
  AppBudgetRoute: typeof AppBudgetRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppHoldingsRoute: typeof AppHoldingsRoute
  AppNewMeRoute: typeof AppNewMeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAttackModeRoute: AppAttackModeRouteWithChildren,
  AppBudgetRoute: AppBudgetRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppHoldingsRoute: AppHoldingsRoute,
  AppNewMeRoute: AppNewMeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  KiteCallbackRoute: KiteCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
